[project]
name = "padel-tracker"
version = "0.4.5"
description = "App to keep track of Padel matches"
readme = "README.md"
requires-python = ">=3.13.4, <3.14"
authors = [
    {name = "Pierre Letousey"},
]
dependencies = [
    "streamlit>=1.47", # For UI
    "streamlit-js-eval>=0.1.7", # For UI
    "sqlmodel>=0.0.27", # Combines sqlalchemy and pydantic
    "psycopg2-binary>=2.9.11", # For PostgreSQL com on cloud-hosted db
    "python-dotenv>=1.0.1", # Secret management in .env file (for cloud-hosted db)
    "pandas>=2.2.3", # Manage some data/statistics as dataframe
    "authlib>=1.4.1", # For User management in UI
    "loguru>=0.7.3", # For loggings
]
[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "ruff>=0.9.6",
    "alembic>=1.16.0", # For database migrations
    "pytest>=8.3.4",
    "pytest-cov>=6.2.1",
    "pytest-env>=1.1.5",
]
cli = [
    "typer>=0.16.1",
]
wakeup = [
    "selenium>=4.29",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
padel-tracker = "padel_tracker.cli:app"

[project.urls]
Repository = "https://github.com/poulpe/padel-tracker"

[tool.ruff]
lint.ignore = [
    "F821", # Must for compatibility with SQLModel Relationship ("name not defined")
]
lint.extend-select = ["N"] # Enforce pep8 naming convention compliance
exclude = ["src/padel_tracker/database/migrations/versions/*.py"]

[tool.ty]
src.exclude = ["tests/*", "src/padel_tracker/database/migrations/*"]
rules.invalid-parameter-default = "ignore"
rules.unresolved-reference = "ignore"
rules.unresolved-attribute = "ignore"

[tool.alembic]
script_location = "src/padel_tracker/database/migrations"
prepend_sys_path = ["."]
[[tool.alembic.post_write_hooks]]
name = "black"
type = "console_scripts"
entrypoint = "black"

[tool.pytest.ini_options]
markers = [
    "ui",
]
env = [
  "db_mode=local",
  "run_mode=test"
]
