[project]
name = "padel-tracker"
version = "0.3.2"
description = "App to keep track of Padel matches"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Pierre Letousey"},
]
dependencies = [
    "streamlit>=1.42", # For UI
    "streamlit-js-eval", # For UI
    "sqlmodel", # Combines sqlalchemy and pydantic
    "psycopg2-binary", # For PostgreSQL com on cloud-hosted db
    "supabase", # For PostgreSQL com on cloud-hosted db
    "python-dotenv", # Secret management in .env file (for cloud-hosted db)
    "pandas",
    "authlib>=1.4.1", # For User management in UI
    "email-validator",
]
[project.optional-dependencies]
dev = [
    "alembic", # For database migrations
    "pytest",
    "coverage",
]

[build-system]
requires = ["setuptools>=64.0.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
padel-tracker = "padel_tracker.main:run_streamlit_app"

[project.urls]
Repository = "https://github.com/poulpe/padel-tracker"

#[tool.black]
#extend-exclude = "src/padel_tracker/database/migrations/versions/.*"

[tool.ruff]
lint.ignore = [
    "E402", # Import not all on top of file
    "E501", # Line too long : balek, managed by Black
    "F821", # Must for compatibility with SQLModel Relationship ("name not defined")
]
exclude = ["src/padel_tracker/database/migrations/versions/*.py"]

[tool.pytest.ini_options]
addopts = "--ignore=examples/" # --doctest-modules
