"""add_matchid_to_teamelohistory

Revision ID: 21e0aad4eefd
Revises: 7b1fd11de66c
Create Date: 2025-02-04 12:56:24.297558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "21e0aad4eefd"
down_revision: Union[str, None] = "7b1fd11de66c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teameloratinghistory", sa.Column("match_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(None, "teameloratinghistory", "match", ["match_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teameloratinghistory", type_="foreignkey")
    op.drop_column("teameloratinghistory", "match_id")
    # ### end Alembic commands ###
