"""add_private_leagues

Revision ID: 4f7307cead48
Revises: 92d6a6aec427
Create Date: 2025-02-21 17:14:20.390715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4f7307cead48"
down_revision: Union[str, None] = "92d6a6aec427"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linkleagueadminuser",
        sa.Column("league_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("league_id", "user_id"),
    )
    op.add_column("league", sa.Column("is_private", sa.Boolean(), nullable=True))
    op.add_column(
        "league",
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("league", "description")
    op.drop_column("league", "is_private")
    op.drop_table("linkleagueadminuser")
    # ### end Alembic commands ###
