"""fix_match_teams

Revision ID: 502b1da607dc
Revises: 4f7307cead48
Create Date: 2025-02-26 00:39:58.123672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "502b1da607dc"
down_revision: Union[str, None] = "4f7307cead48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match",
        sa.Column("team1_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "match",
        sa.Column("team2_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "team2_name")
    op.drop_column("match", "team1_name")
    # ### end Alembic commands ###
