"""add match_name to elohistory

Revision ID: 535aaf00283a
Revises: 54457e289b87
Create Date: 2025-01-29 17:20:33.586534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "535aaf00283a"
down_revision: Union[str, None] = "54457e289b87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eloratinghistory",
        sa.Column("match_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "teameloratinghistory",
        sa.Column("match_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teameloratinghistory", "match_name")
    op.drop_column("eloratinghistory", "match_name")
    # ### end Alembic commands ###
