"""first_version

Revision ID: 54457e289b87
Revises: 
Create Date: 2025-01-26 18:14:22.174352

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "54457e289b87"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
