"""added leagues

Revision ID: 7b1fd11de66c
Revises: f9eef5663708
Create Date: 2025-02-03 18:45:04.476062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7b1fd11de66c"
down_revision: Union[str, None] = "f9eef5663708"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "league",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nb_matches", sa.Integer(), nullable=False),
        sa.Column("nb_players", sa.Integer(), nullable=False),
        sa.Column("last_match_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_league_name"), "league", ["name"], unique=False)
    op.create_table(
        "linkleaguematch",
        sa.Column("league_id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("league_id", "match_id"),
    )
    op.create_table(
        "linkplayerleague",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("league_id", sa.Uuid(), nullable=False),
        sa.Column("player_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("league_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("best_rank", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "league_id"),
    )
    op.create_index(
        op.f("ix_linkplayerleague_rank"), "linkplayerleague", ["rank"], unique=False
    )
    op.create_table(
        "linkteamleague",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("league_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "league_id"),
    )
    op.add_column("eloratinghistory", sa.Column("match_id", sa.Uuid(), nullable=True))
    op.add_column("eloratinghistory", sa.Column("league_id", sa.Uuid(), nullable=True))
    op.add_column(
        "eloratinghistory",
        sa.Column("league_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(None, "eloratinghistory", "match", ["match_id"], ["id"])
    op.create_foreign_key(None, "eloratinghistory", "league", ["league_id"], ["id"])
    op.add_column(
        "match",
        sa.Column("league_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_index("ix_player_rank", table_name="player")
    op.drop_column("player", "rank")
    op.drop_column("player", "best_rank")
    op.add_column("rankhistory", sa.Column("league_id", sa.Uuid(), nullable=True))
    op.add_column(
        "rankhistory",
        sa.Column("league_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "rankhistory", "player_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_foreign_key(None, "rankhistory", "league", ["league_id"], ["id"])
    op.add_column(
        "teameloratinghistory", sa.Column("league_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "teameloratinghistory",
        sa.Column("league_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(None, "teameloratinghistory", "league", ["league_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teameloratinghistory", type_="foreignkey")
    op.drop_column("teameloratinghistory", "league_name")
    op.drop_column("teameloratinghistory", "league_id")
    op.drop_constraint(None, "rankhistory", type_="foreignkey")
    op.alter_column(
        "rankhistory", "player_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("rankhistory", "league_name")
    op.drop_column("rankhistory", "league_id")
    op.add_column(
        "player",
        sa.Column("best_rank", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player", sa.Column("rank", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_player_rank", "player", ["rank"], unique=False)
    op.drop_column("match", "league_name")
    op.drop_constraint(None, "eloratinghistory", type_="foreignkey")
    op.drop_constraint(None, "eloratinghistory", type_="foreignkey")
    op.drop_column("eloratinghistory", "league_name")
    op.drop_column("eloratinghistory", "league_id")
    op.drop_column("eloratinghistory", "match_id")
    op.drop_table("linkteamleague")
    op.drop_index(op.f("ix_linkplayerleague_rank"), table_name="linkplayerleague")
    op.drop_table("linkplayerleague")
    op.drop_table("linkleaguematch")
    op.drop_index(op.f("ix_league_name"), table_name="league")
    op.drop_table("league")
    # ### end Alembic commands ###
