"""add_is_friendly_to_match

Revision ID: cab9b2f3866f
Revises: f822d258a870
Create Date: 2025-08-13 12:03:14.634123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cab9b2f3866f"
down_revision: Union[str, None] = "f822d258a870"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match",
        sa.Column(
            "is_friendly", sa.Boolean(), nullable=False, server_default=sa.text("FALSE")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "is_friendly")
    # ### end Alembic commands ###
