"""log_user_visits

Revision ID: d3d3615eda4b
Revises: 502b1da607dc
Create Date: 2025-04-10 19:53:51.218105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d3d3615eda4b"
down_revision: Union[str, None] = "502b1da607dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "nb_visits",
            sa.Integer(),
            default=0,
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "user", sa.Column("last_visit_date", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "nb_visits")
    op.drop_column("user", "last_visit_date")
    # ### end Alembic commands ###
