"""match: added nb_won_sets_diff and nb_won_games_diff

Revision ID: e0720ed51427
Revises: e64427aa42b7
Create Date: 2025-01-24 17:55:35.091156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0720ed51427'
down_revision: Union[str, None] = 'e64427aa42b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('nb_won_sets_diff', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('nb_won_games_diff', sa.Integer(), nullable=True))
    op.alter_column('match', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('match', 'nb_won_games_diff')
    op.drop_column('match', 'nb_won_sets_diff')
    # ### end Alembic commands ###
