"""added events

Revision ID: f822d258a870
Revises: d3d3615eda4b
Create Date: 2025-08-06 22:05:57.403421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f822d258a870"
down_revision: Union[str, None] = "d3d3615eda4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_date"), "event", ["date"], unique=False)
    op.create_index(op.f("ix_event_end_date"), "event", ["end_date"], unique=False)
    op.create_table(
        "linkeventleague",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("league_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "league_id"),
    )
    # op.alter_column("match", "team1_name", existing_type=sa.VARCHAR(), nullable=False)
    # op.alter_column("match", "team2_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column("match", "team2_name", existing_type=sa.VARCHAR(), nullable=True)
    # op.alter_column("match", "team1_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("linkeventleague")
    op.drop_index(op.f("ix_event_end_date"), table_name="event")
    op.drop_index(op.f("ix_event_date"), table_name="event")
    op.drop_table("event")
    # ### end Alembic commands ###
