name: season_reset

on:
  workflow_dispatch:  # Manually
  schedule:
    - cron: "0 12 3 10 *"  # October 3rd (12:00 UTC) every year (anniversary date)

jobs:
  season_reset:
    runs-on: ubuntu-latest
    environment: test  # prod or test
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Launch season_reset Python script
        run: uv run ./scripts/season_reset.py
        env:
          db_mode: ${{ vars.DB_MODE }}
          run_mode: ${{ vars.RUN_MODE }}
          db_url_cloud_prod: ${{ secrets.DB_URL_CLOUD_PROD }}
          db_url_cloud_test: ${{ secrets.DB_URL_CLOUD_TEST }}
