name: tests

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI
  pull_request:
    paths: # Only in case of changes in the following files/folders
      - "src/**"
      - "tests/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".gitignore"
  push:
    branches: [ main ] # To trigger code coverage on main
    paths: # Only in case of changes in the following files/folders
      - "src/**"
      - "tests/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".gitignore"

jobs:
  test-lint:
    name: Check linting (black + ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Setup venv & install dependencies
        run: uv sync --extra dev

      - name: Check formatting with Black
        run: uv run black . --check

      - name: Check linting with Ruff
        run: uv run ruff check

  test-pytest:
    name: Test with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Setup venv & install dependencies
        run: uv sync --extra dev
          
      - name: Run pytest
        run: uv run pytest --cov --cov-branch --cov-report=xml --junitxml=junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
