# For preventing streamlit app from going to "inactivity" mode of Community Cloud

name: wakeup_app

on:
  workflow_dispatch:  # Manually
  schedule:
    - cron: "0 */22 * * *" # Each 22h

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Wakeup Streamlit app (Community Cloud)
        run: uv run --no-project --with "selenium>=4.29" ./scripts/wakeup_app.py
