# For preventing streamlit app from going to "inactivity" mode of Community Cloud

name: wakeup_app

on:
  workflow_dispatch:  # Manually
  schedule:
    - cron: "0 */22 * * *" # Each 22h

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Wakeup Streamlit app (Community Cloud)
        run: |
           python -c "import requests; r = requests.get(r'https://poulpe-padel-tracker.streamlit.app/', timeout=10); print(f'{r.status_code=}'); exit(1) if (r.status_code < 200 or r.status_code >= 300) else exit(0)"
